### ISSUE TITLE
When upgrading/updating modules it doesn't let me due --> \node_modules\material-ui-phone-number: Appears to be a git repo or submodule.

### ISSUE THREAD

**Issue by maielo** [alexplumb/material-ui-phone-number#10]
Hello, 
when i was tryin gto upgrade packages in my project it seems yours package blocked the upgrade. When i checked the files in `node_modules/material-ui-phone-number` it seems it containes `.git` folder (so the npm thinks its a git submodule and refuses it to remove it or upgrade it ). Could you add it to .gitignore ? or publish it without it ?

error
```
npm ERR! path C:\web_projects\<project>\node_modules\material-ui-phone-number 
npm ERR! code EISGIT 
npm ERR! git C:\web_projects\<project>\node_modules\material-ui-phone-number: Appears to be a git repo or submodule. 
npm ERR! git     C:\web_projects\<project>\node_modules\material-ui-phone-number
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

```

Thanks

**Comment by alexplumb** [comment]
Thanks for the heads-up. Fixed in `1.6.0`
