### ISSUE TITLE
Is there a way to override style?

### ISSUE THREAD

**Issue by jonathangiamp** [alexplumb/material-ui-phone-number#12]
Hi everyone 👋 

Firstly, thanks for this library, it is very cool. I would like to know if is there a way to override style property like main color? I saw that the library use the default material-ui theme and I didn't find anything to override it. In a perfect world, that could be very cool to be able to pass our material-ui theme to override default one.

Thank you very much!

**Comment by benesva4** [comment]
Hey, I solved it by wrapping it in the custom theme, in which I defined styles for used components. Not the best, but it works.
