### ISSUE TITLE
Package Versions not appropriately using dependencies vs peer dependencies. 

### ISSUE THREAD

**Issue by samparnell** [alexplumb/material-ui-phone-number#13]
The following dependencies are declared in the package.json for this package. 

```
"dependencies": {
    "@material-ui/core": "^3.9.3",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "peerDependencies": {
    "@material-ui/core": "^3",
    "react": ">=16",
    "react-dom": ">=16"
  }
```

Ideally you should only have these as peer dependencies. With the current set up when you increment say @material-ui/core to ^3.9.3 but the app that uses it has a version of ^3.9.2 your module will force npm to update the version. Worse, if the app has an exact version of 3.9.2 this will result in the bundle having two versions of material ui as npm will ensure that both versions are matched separately. 

So that you can run tests etc you can include the current dependencies in your devDependencies and then list peerDependencies with the minimum required version. If the package really supports material ui 3.* then your current setup will still end up installing 3.9.3 whether it is needed or not.

**Comment by alexplumb** [comment]
Thanks for the heads-up - this is fixed now
