### ISSUE TITLE
Material UI import results in broad inclusion of packages

### ISSUE THREAD

**Issue by samparnell** [alexplumb/material-ui-phone-number#14]
In https://github.com/alexplumb/material-ui-phone-number/blob/master/src/components/index.jsx the following code results in the entire material ui library being included as a dependency
```
import {
  TextField, InputAdornment, Button, Menu, Divider, RootRef,
} from '@material-ui/core';
```
Ideally this would only include the desired components and the material ui folks could probably make that better....but for now if you include explicitly the size of the install package would be greatly reduced. 
```
import Button from '@material-ui/core/Button'; 
import Divider from '@material-ui/core/Divider'; 
import InputAdornment from '@material-ui/core/InputAdornment';
import Menu from '@material-ui/core/Menu';
import RootRef from '@material-ui/core/RootRef';
import TextField from '@material-ui/core/TextField'; 
```

**Comment by alexplumb** [comment]
These packages were already being excluded from the build thanks to webpack, but I've gone ahead and made this change in `2.0.0` just to be more explicit. Thanks!
