### ISSUE TITLE
flags.png is base64 encoded in dist, but required by styles as file.

### ISSUE THREAD

**Issue by whittomd** [alexplumb/material-ui-phone-number#2]
In index.jsx:

const styles = () => ({
  flag: {
    height: 16,
    width: 11,
    background: 'url("./flags.png")',
  },
  flagButton: {
    minWidth: 30,
    padding: 0,
  },
  positionStart: {
    position: 'relative',
  },
});

This causes an attempt to load the file itself, even though it is already included in base64 uri.

**Comment by alexplumb** [comment]
Thanks for the heads-up. This should be fixed now.
