### ISSUE TITLE
missing "margin" prop for TextField

### ISSUE THREAD

**Issue by jeromevvb** [alexplumb/material-ui-phone-number#27]
Hello!

Thanks a lot for this component!
i just noticed that the prop "margin" for TextField is missing.
check here https://material-ui.com/api/text-field/#textfield-api

is it possible to add it?
thanks!

**Comment by jeromevvb** [comment]
sorry, i just saw #26   +1 for merge

**Comment by alexplumb** [comment]
@jeromevvb Hey, sorry for the delay on this - rather than just adding the `margin` prop as per the PR, I've instead added support for every `TextField` prop.
