### ISSUE TITLE
Switch to 2.2.0 from 2.1.0 broke the app for some reason

### ISSUE THREAD

**Issue by masbaehr** [alexplumb/material-ui-phone-number#28]
This is the error i'm getting with 2.2.0 which does not happen with 2.1.0

Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

e.updateFormattedNumber

**Comment by alexplumb** [comment]
Thanks for the heads-up, @masbaehr. Can you share your code for this component?

**Comment by alexplumb** [comment]
@masbaehr I've released `2.2.1` - please see if this fixes it

**Comment by masbaehr** [comment]
Hey thanks for the quick fix, it works again. ;-)
