### ISSUE TITLE
Support the `error` prop

### ISSUE THREAD

**Issue by ceefour** [alexplumb/material-ui-phone-number#3]
Thank you @alexplumb for creating this! 👍 

Please support the [`error` prop like `TextField`](https://material-ui.com/api/text-field/#props), so that the `label` and `helperText` is displayed in red styling like Material UI standard theming.

Thank you very much!

**Comment by alexplumb** [comment]
@ceefour Sorry for the delay in getting to this. The `error` prop should be getting set on the `TextField` when the phone number is invalid. Is this not happening for you?
