### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by callmeberzerker** [alexplumb/material-ui-phone-number#34]
Probably the core issue is the same as with the react-phone-input-2: https://github.com/bl00mber/react-phone-input-2/issues/126

This only happens when you build the bundle with node_env PRODUCTION.

**Comment by ibrahim-ih** [comment]
to solve this problem temporarily build as dev
`build": "webpack --config webpack.config.build.js --progress --mode development`

**Comment by anking** [comment]
I have the same problem, is there an eta on a long-term solution for this yet? --mode development is not an option

**Comment by callmeberzerker** [comment]
@anking downgrade the version to 2.0.0 until they fix it.

**Comment by anking** [comment]
> @anking downgrade the version to 2.0.0 until they fix it.

This did not fix a problem for me. After I recompile and re-deploy with 2.0.0 i still get the same issue.
![image](https://user-images.githubusercontent.com/9019734/68590461-87cbbc80-045c-11ea-8f10-be58d68788ca.png)

**Comment by ErAz7** [comment]
any solution for this?
this is a huge pain

**Comment by ibrahim-ih** [comment]
> any solution for this?
> this is a huge pain
> at least any update to know if you're working on to solve and if so, what is your estimation about bug fix version ?

try to use my forked repos until they solve the problem
`"material-ui-phone-number": "https://github.com/ibrahim-ih/material-ui-phone-number.git"`

**Comment by ErAz7** [comment]
> > any solution for this?
> > this is a huge pain
> > at least any update to know if you're working on to solve and if so, what is your estimation about bug fix version ?
> 
> try to use my forked repos until they solve the problem
> `"material-ui-phone-number": "https://github.com/ibrahim-ih/material-ui-phone-number.git"`

Thanks
I'll try

**Comment by alexplumb** [comment]
This should be resolved in `material-ui-phone-number@2.2.4`

**Comment by boraicho** [comment]
still not working

**Comment by alexplumb** [comment]
@boraicho Can you provide a code repo where it's failing?

**Comment by abhijit-padhy** [comment]
@alexplumb  While using `material-ui-phone-number@2.2.4` I am getting below errors:
 ```
Module not found: Error: Can't resolve '@material-ui/core/Button' in ‘…/node_modules/material-ui-phone-number/dist'
 Module not found: Error: Can't resolve '@material-ui/core/Divider' in ‘…/node_modules/material-ui-phone-number/dist' 
```
And more similar errors
