### ISSUE TITLE
Shows many flags for US/Canada

### ISSUE THREAD

**Issue by prionkor** [alexplumb/material-ui-phone-number#41]
How to show one flag for one country? The script is showing US/Canada flag for each of the local area.

**Comment by sahanaravi** [comment]
add the property-  disableAreaCodes={true}

**Comment by raphaelpinel** [comment]
But if you set the property- disableAreaCodes={true}, it doesn't recognize Canadian phones (it says it is US). It would be great to display only the US/Canada flag in the list, but still be able to recognize them behind the scene
