### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by felipevargas-gaivota** [alexplumb/material-ui-phone-number#5]
In the documentation, you say that the props containerStyle and inputStyle are options, but after trying to use them (and checking the code) I noticed that those doesn't work.

**Comment by alexplumb** [comment]
Thanks for the heads-up @felipevargas-gaivota. I neglected to remove that part of the documentation when I forked this. Should be good now! :)

**Comment by felipevargas-gaivota** [comment]
Sweet @alexplumb, ty for the quick update! Have a nice day :)
