### ISSUE TITLE
Country Menu not attached to field

### ISSUE THREAD

**Issue by wkerswell-gresham** [alexplumb/material-ui-phone-number#50]
Hi, 

When trying to use the phone number input I am having trouble getting the menu to display under the input like a normal select input. I have managed to reproduce it here. 

https://codesandbox.io/s/mui-phone-number-9qomr

Is there a way to get the menu to display like this? 
![Screenshot 2020-02-06 at 15 43 57](https://user-images.githubusercontent.com/20516520/73952924-8abd3880-48f7-11ea-95cd-5c08f09f472e.png)

Many thanks

**Comment by wkerswell-gresham** [comment]
Had a look and found that if I comment out the `paperProps` on the `<menu>` the list is positioned correctly but then the menu isn't scrolled to the correct location. Any have an idea why the paper props could be interfering with the menu popper anchorEl?

**Comment by wkerswell-gresham** [comment]
Please can I get someone to review my PR

**Comment by sdennett55** [comment]
@alexplumb

**Comment by wkerswell-gresham** [comment]
Happy to become a maintainer if you don't have the time.

**Comment by alexplumb** [comment]
Hi @wkerswell-gresham thanks for putting in the legwork - I've merged your branch and am putting together a release right away. Sorry for the delay on this.

If you'd like to become a maintainer after this is deployed, I'd love to see another pull request (to either add a feature or fix a bug) and then we can discuss it further.
