### ISSUE TITLE
Menu appears at top-left of the screen

### ISSUE THREAD

**Issue by AntwanSherif** [alexplumb/material-ui-phone-number#52]
Hi, 

I have the following issue when using this component inside my app, not sure though what's the problem.

Menu appears at top-left of the screen.
<img width="1243" alt="Screen Shot 2020-03-06 at 4 48 26 PM" src="https://user-images.githubusercontent.com/24325533/76093889-63c35680-5fca-11ea-8f21-99a3bf4658ae.png">

**Comment by cngeru** [comment]
Getting the same

**Comment by Toshiuk** [comment]
Take a look at it, it fixed to me :)
https://github.com/alexplumb/material-ui-phone-number/pull/51#issuecomment-601647222

**Comment by alexplumb** [comment]
Resolved in `2.2.6`
