### ISSUE TITLE
Increasing the flag size

### ISSUE THREAD

**Issue by BagchiMB** [alexplumb/material-ui-phone-number#62]
Is there any way to increase the size of the flag ? I am stuck with it any changes I do to the width and height, other flags starts exposing as it is basicaly one chunk of image containing all the flags ?

**Comment by MartinDesrosiers** [comment]
Hi @BagchiMB,
I'm not a developer of this library, but I found a solution.
You have to use the transform scale CSS property on the parent element.
Ex:
```
.MuiButton-label {
  transform: scale(1.5);
}
```
I hope it helps you!
