### ISSUE TITLE
Setting State inside onChage does not work.

### ISSUE THREAD

**Issue by bip3r** [alexplumb/material-ui-phone-number#7]
i can't set state inside the onChange. i have seen this error accured already, but yet no solution found.

`  
  phoneInput: (value, country) => {
      const phoneNum = value;
      console.log(phoneNum, country);
      setUser({ ...user, Phone: value });
    },
`
this is the code for the onChange.
the result of this is not error, but a rather weird behavior; the input will not show the number, and in the state it'll update 1 number top ("+9721")

**Comment by alexplumb** [comment]
Thanks for the example - this should be fixed now! :)
