### ISSUE TITLE
Does not work with @material-ui/core@5.0.0-alpha.5 or higher

### ISSUE THREAD

**Issue by dvakatsiienko** [alexplumb/material-ui-phone-number#72]
Using `@material-ui/core@5.0.0-alpha.5` and higher, `material-ui-phone-number` produces the following error:

```
error - ./node_modules/material-ui-phone-number/dist/index.js:1:52871
Module not found: Can't resolve '@material-ui/core/RootRef'
```

**Comment by mirshahnewaz** [comment]
any idea when this library could be updated to work with material ui version 5?
thanks

**Comment by edelCustodio** [comment]
I have the same issue with this library.
