### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by 23subbhashit** [alexplumb/material-ui-phone-number#74]
When i tried using it ,
```
<MuiPhoneNumber
                defaultCountry={"in"}
                onChange={handleOnChange}
                required
                id="phone"
                name="phone"
                value={value}
                
              />
```
It was not having borders around it as shown in the official readme of material-ui-phone-number.
It was showing like this.
![Phone (2)](https://user-images.githubusercontent.com/43717493/93337826-4a3b7b00-f847-11ea-804f-2193fe688f06.png)
Is there any way to add border to it?

**Comment by DavidScicluna** [comment]
You can add Material-UI props to it, for example:
```
<MuiPhoneNumber
    defaultCountry={"in"}
    onChange={handleOnChange}
    required
    id="phone"
    name="phone"
    value={value}
    fullWidth
    size="small"
    variant="outlined"
/>
```

**Comment by 23subbhashit** [comment]
Thanks for this👍
