### ISSUE TITLE
How to set fullWidth 

### ISSUE THREAD

**Issue by AlmogRnD** [alexplumb/material-ui-phone-number#8]
Hi Great package and amazing work, I was wondering what the best approach would be to set the input field to be full width to match the rest of my inputs attached screenshots. 
<img width="504" alt="Screen Shot 2019-04-03 at 3 07 24 PM" src="https://user-images.githubusercontent.com/169507/55452184-3768c280-5622-11e9-8afa-ebe980d70867.png">

**Comment by alexplumb** [comment]
Thanks for the kind words, @AlmogRnD - I've just published `1.5.0`, which includes support for the `fullWidth` property.

**Comment by corneliushka** [comment]
I believe the issue is because of <MenuItem/> tags displayed in the dropdown, and these contain a lot of mui layer ('the touch ripple effect' on click) that impacts and weight in the DOM. 

The not MUI version (react-phone-input-2) has a span in less, so it's faster.
