### ISSUE TITLE
InputClass styles do not get applied at all

### ISSUE THREAD

**Issue by Brian611** [alexplumb/material-ui-phone-number#9]
I am unable to apply styles to the textfield. see example bellow:

const styles = (theme: Theme) => createStyles({
    muiPhoneNumberClass: {
        width: '250px',
    },
});

<MuiPhoneNumber InputClass={classes.muiPhoneNumberClass} defaultCountry={'gb'} onlyCountries={['gb']} onChange={setMobileNumber} />

Side Note: Please do remove your .git folder as npm complains when we try to do another install of another package.

**Comment by alexplumb** [comment]
Sorry for taking so long to get to this issue. Please make sure you specify `inputClass` instead of `InputClass` - the first part needs to be lowercase! :)

I've also released an update that should fix the .git issue.
