### ISSUE TITLE
802 area code not recognized

### ISSUE THREAD

**Issue by Devon66h** [alexplumb/material-ui-phone-number#90]
Vermont's (802) area code is not being recognized by phone input (see video attached). 

Just FYI, this is the area code for the whole state.

https://user-images.githubusercontent.com/3513163/120660349-3aa3a700-c455-11eb-978a-5e5a0ec5b5d8.mov

**Comment by james-lukensow** [comment]
Not sure why this is closed as I'm seeing 802 and 858 not being recognized as valid on the latest build.
