### ISSUE TITLE
Need a maintainer?

### ISSUE THREAD

**Issue by bherila** [alexplumb/material-ui-phone-number#94]
@alexplumb  I reached out to you on LinkedIn about potentially helping out as a maintainer of this package. Please let me know if it's something you would consider. 

It would be great if the existing community could continue to benefit from bug fixes and updates, and there are several PRs already here that are worthy of merging.

Otherwise, I'll have to publish a fork of this package to continue development ☹️

**Comment by alexplumb** [comment]
@bherila Sorry - I don't see your message in Linkedin. Wrong person, maybe Definitely happy to bring on a maintainer. This package needs a lot of work to support Material-UI 5 (among other things) and it's just not something I have the time to commit to right now.

**Comment by alexplumb** [comment]
I've taken a look at your repos. Looks good - added as a collaborator. I'll see if I can carve out some time to update the eslint config and packages.

**Comment by bherila** [comment]
Seems like https://github.com/alexplumb/material-ui-phone-number/pull/93 might bring MUI5 support, will take a look ater
